{
 "title": "Azure Application Gataway & WAF log",
 "description": "Azure Application Gataway & WAF ",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "AzureDataSource",
    "label": "AzureDataSource",
    "query": "grafana-azure-monitor-datasource"
   },
   {
    "name": "Subscription",
    "query": {}
   },
   {
    "name": "ResourceGroup",
    "label": "ResourceGroup",
    "query": "MC_binder-prod-k8s-rg_binder-prod-cluster_westeurope"
   },
   {
    "name": "Namespace",
    "label": "Namespace",
    "query": {}
   },
   {
    "name": "ResourceName",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Current Compute Units",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "intersectTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "7d59ab60-d04b-43b7-8eab-8c318b8a45bb"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.Network/applicationGateways",
      "metricName": "ComputeUnits",
      "metricNamespace": "microsoft.network/applicationgateways",
      "region": "",
      "resources": [
       {
        "metricNamespace": "microsoft.network/applicationgateways",
        "region": "",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:2374", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:2375", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:2376", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:2377", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:2378", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:2379", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:2380", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:2381", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:2382", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Current Capacity Units",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "intersectTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "7d59ab60-d04b-43b7-8eab-8c318b8a45bb"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.Network/applicationGateways",
      "metricName": "CapacityUnits",
      "metricNamespace": "microsoft.network/applicationgateways",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/applicationGateways",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:2864", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:2865", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:2866", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:2867", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:2868", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:2869", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:2870", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:2871", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:2872", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Healthy Host Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "intersectTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "7d59ab60-d04b-43b7-8eab-8c318b8a45bb"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [
       { "$$hashKey": "object:2205", "text": "None", "value": "None" },
       { "$$hashKey": "object:2206", "text": "BackendPool HttpSettings", "value": "BackendSettingsPool" }
      ],
      "metricDefinition": "Microsoft.Network/applicationGateways",
      "metricName": "HealthyHostCount",
      "metricNamespace": "microsoft.network/applicationgateways",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/applicationGateways",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:2196", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:2197", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:2198", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:2199", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:2200", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:2201", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:2202", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:2203", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:2204", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Client TLS Protocol",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "intersectTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "7d59ab60-d04b-43b7-8eab-8c318b8a45bb"
     },
     "azureMonitor": {
      "aggOptions": [ "Total" ],
      "aggregation": "Total",
      "alias": "{{dimensionvalue}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "TlsProtocol",
        "filters": [],
        "operator": "eq"
       }
      ],
      "dimensions": [
       { "$$hashKey": "object:4152", "text": "None", "value": "None" },
       { "$$hashKey": "object:4153", "text": "Listener", "value": "Listener" },
       { "$$hashKey": "object:4154", "text": "TLS Protocol", "value": "TlsProtocol" }
      ],
      "metricDefinition": "Microsoft.Network/applicationGateways",
      "metricName": "TlsProtocol",
      "metricNamespace": "microsoft.network/applicationgateways",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/applicationGateways",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:4143", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:4144", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:4145", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:4146", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:4147", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:4148", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:4149", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:4150", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:4151", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "intersectTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "7d59ab60-d04b-43b7-8eab-8c318b8a45bb"
     },
     "azureMonitor": {
      "aggOptions": [ "Total" ],
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [
       { "$$hashKey": "object:2536", "text": "None", "value": "None" },
       { "$$hashKey": "object:2537", "text": "BackendPool HttpSettings", "value": "BackendSettingsPool" }
      ],
      "metricDefinition": "Microsoft.Network/applicationGateways",
      "metricName": "TotalRequests",
      "metricNamespace": "microsoft.network/applicationgateways",
      "resources": [
       {
        "metricNamespace": "microsoft.network/applicationgateways",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:2527", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:2528", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:2529", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:2530", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:2531", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:2532", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:2533", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:2534", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:2535", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Current Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "intersectTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "7d59ab60-d04b-43b7-8eab-8c318b8a45bb"
     },
     "azureMonitor": {
      "aggOptions": [ "Total" ],
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.Network/applicationGateways",
      "metricName": "CurrentConnections",
      "metricNamespace": "microsoft.network/applicationgateways",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/applicationGateways",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:2449", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:2450", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:2451", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:2452", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:2453", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:2454", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:2455", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:2456", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:2457", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "New Connections per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "intersectTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "7d59ab60-d04b-43b7-8eab-8c318b8a45bb"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.Network/applicationGateways",
      "metricName": "NewConnectionsPerSecond",
      "metricNamespace": "microsoft.network/applicationgateways",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/applicationGateways",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:2640", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:2641", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:2642", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:2643", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:2644", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:2645", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:2646", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:2647", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:2648", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "intersectTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "7d59ab60-d04b-43b7-8eab-8c318b8a45bb"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.Network/applicationGateways",
      "metricName": "Throughput",
      "metricNamespace": "microsoft.network/applicationgateways",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/applicationGateways",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:2577", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:2578", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:2579", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:2580", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:2581", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:2582", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:2583", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:2584", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:2585", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Controller Success Rate (non-4|5xx responses)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "intersectTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "7d59ab60-d04b-43b7-8eab-8c318b8a45bb"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.network/applicationgateways",
      "dimensionFilters": [],
      "dimensions": [
       { "$$hashKey": "object:2205", "text": "None", "value": "None" },
       { "$$hashKey": "object:2206", "text": "BackendPool HttpSettings", "value": "BackendSettingsPool" }
      ],
      "metricDefinition": "Microsoft.Network/applicationGateways",
      "metricName": "TotalRequests",
      "metricNamespace": "microsoft.network/applicationgateways",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/applicationGateways",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:2196", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:2197", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:2198", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:2199", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:2200", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:2201", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:2202", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:2203", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:2204", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$Subscription"
    },
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "intersectTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "7d59ab60-d04b-43b7-8eab-8c318b8a45bb"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [
       { "$$hashKey": "object:2205", "text": "None", "value": "None" },
       { "$$hashKey": "object:2206", "text": "BackendPool HttpSettings", "value": "BackendSettingsPool" }
      ],
      "metricDefinition": "Microsoft.Network/applicationGateways",
      "metricName": "FailedRequests",
      "metricNamespace": "microsoft.network/applicationgateways",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/applicationGateways",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:2196", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:2197", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:2198", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:2199", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:2200", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:2201", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:2202", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:2203", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:2204", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Networking Transfer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "intersectTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "7d59ab60-d04b-43b7-8eab-8c318b8a45bb"
     },
     "azureMonitor": {
      "aggOptions": [ "Total" ],
      "aggregation": "Total",
      "alias": "{{metric}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [
       { "$$hashKey": "object:4492", "text": "None", "value": "None" },
       { "$$hashKey": "object:4493", "text": "Listener", "value": "Listener" }
      ],
      "metricDefinition": "Microsoft.Network/applicationGateways",
      "metricName": "BytesSent",
      "metricNamespace": "microsoft.network/applicationgateways",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/applicationGateways",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:4483", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:4484", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:4485", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:4486", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:4487", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:4488", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:4489", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:4490", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:4491", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$Subscription"
    },
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "intersectTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "7d59ab60-d04b-43b7-8eab-8c318b8a45bb"
     },
     "azureMonitor": {
      "aggOptions": [ "Total" ],
      "aggregation": "Total",
      "alias": "{{metric}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [
       { "$$hashKey": "object:4515", "text": "None", "value": "None" },
       { "$$hashKey": "object:4516", "text": "Listener", "value": "Listener" }
      ],
      "metricDefinition": "Microsoft.Network/applicationGateways",
      "metricName": "BytesReceived",
      "metricNamespace": "microsoft.network/applicationgateways",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/applicationGateways",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:4506", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:4507", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:4508", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:4509", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:4510", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:4511", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:4512", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:4513", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:4514", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Application gateway total time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "intersectTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "7d59ab60-d04b-43b7-8eab-8c318b8a45bb"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [
       { "$$hashKey": "object:2984", "text": "None", "value": "None" },
       { "$$hashKey": "object:2985", "text": "Listener", "value": "Listener" }
      ],
      "metricDefinition": "Microsoft.Network/applicationGateways",
      "metricName": "ApplicationGatewayTotalTime",
      "metricNamespace": "microsoft.network/applicationgateways",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/applicationGateways",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:2975", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:2976", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:2977", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:2978", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:2979", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:2980", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:2981", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:2982", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:2983", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$Subscription"
    },
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "intersectTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "7d59ab60-d04b-43b7-8eab-8c318b8a45bb"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [
       { "$$hashKey": "object:3239", "text": "None", "value": "None" },
       { "$$hashKey": "object:3240", "text": "Listener", "value": "Listener" },
       { "$$hashKey": "object:3241", "text": "Backend Server", "value": "BackendServer" },
       { "$$hashKey": "object:3242", "text": "Backend Pool", "value": "BackendPool" },
       { "$$hashKey": "object:3243", "text": "Backend Http Setting", "value": "BackendHttpSetting" }
      ],
      "metricDefinition": "Microsoft.Network/applicationGateways",
      "metricName": "BackendConnectTime",
      "metricNamespace": "microsoft.network/applicationgateways",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/applicationGateways",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:3230", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:3231", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:3232", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:3233", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:3234", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:3235", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:3236", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:3237", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:3238", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$Subscription"
    },
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "intersectTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "7d59ab60-d04b-43b7-8eab-8c318b8a45bb"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [
       { "$$hashKey": "object:3279", "text": "None", "value": "None" },
       { "$$hashKey": "object:3280", "text": "Listener", "value": "Listener" },
       { "$$hashKey": "object:3281", "text": "Backend Server", "value": "BackendServer" },
       { "$$hashKey": "object:3282", "text": "Backend Pool", "value": "BackendPool" },
       { "$$hashKey": "object:3283", "text": "Backend Http Setting", "value": "BackendHttpSetting" }
      ],
      "metricDefinition": "Microsoft.Network/applicationGateways",
      "metricName": "BackendFirstByteResponseTime",
      "metricNamespace": "microsoft.network/applicationgateways",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/applicationGateways",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:3270", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:3271", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:3272", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:3273", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:3274", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:3275", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:3276", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:3277", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:3278", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$Subscription"
    },
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "intersectTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "7d59ab60-d04b-43b7-8eab-8c318b8a45bb"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [
       { "$$hashKey": "object:3315", "text": "None", "value": "None" },
       { "$$hashKey": "object:3316", "text": "Listener", "value": "Listener" },
       { "$$hashKey": "object:3317", "text": "Backend Server", "value": "BackendServer" },
       { "$$hashKey": "object:3318", "text": "Backend Pool", "value": "BackendPool" },
       { "$$hashKey": "object:3319", "text": "Backend Http Setting", "value": "BackendHttpSetting" }
      ],
      "metricDefinition": "Microsoft.Network/applicationGateways",
      "metricName": "BackendLastByteResponseTime",
      "metricNamespace": "microsoft.network/applicationgateways",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/applicationGateways",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:3306", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:3307", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:3308", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:3309", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:3310", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:3311", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:3312", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:3313", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:3314", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Backend Response Status",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "intersectTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "7d59ab60-d04b-43b7-8eab-8c318b8a45bb"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "HttpStatusGroup",
        "filters": [],
        "operator": "eq"
       }
      ],
      "dimensions": [
       { "$$hashKey": "object:2984", "text": "None", "value": "None" },
       { "$$hashKey": "object:2985", "text": "Listener", "value": "Listener" }
      ],
      "metricDefinition": "Microsoft.Network/applicationGateways",
      "metricName": "BackendResponseStatus",
      "metricNamespace": "microsoft.network/applicationgateways",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/applicationGateways",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ResourceName",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:2975", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:2976", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:2977", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:2978", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:2979", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:2980", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:2981", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:2982", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:2983", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "WAF ALL Logs",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "intersectTime": false,
      "query": "AGWFirewallLogs\n| where  Type == \"AGWFirewallLogs\" \n| where TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\n| order by TimeGenerated asc",
      "resources": [
       "/subscriptions/$Subscription/resourceGroups/$ResourceGroup"
      ],
      "resultFormat": "table",
      "workspace": "08934564-b6bd-42d1-9f9f-b777176b0835"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resources": [
       { "resourceGroup": "select", "resourceName": "select" }
      ],
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "9208153d-b7d9-4b82-bbed-8222fc3ed00f"
    }
   ]
  },
  {
   "title": "WAF Block Count from IPs",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "intersectTime": false,
      "query": "AGWFirewallLogs \n| where Action == \"Blocked\"\n| where TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\n| summarize count() by ClientIp, bin(TimeGenerated, $__interval)\n",
      "resources": [
       "/subscriptions/$Subscription/resourceGroups/$ResourceGroup"
      ],
      "resultFormat": "time_series",
      "workspace": "08934564-b6bd-42d1-9f9f-b777176b0835"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resources": [
       { "resourceGroup": "select", "resourceName": "select" }
      ],
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "9208153d-b7d9-4b82-bbed-8222fc3ed00f"
    }
   ]
  },
  {
   "title": "Rules Current percentage",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 9, "x": 7, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "intersectTime": false,
      "query": "AGWFirewallLogs \n| where TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\n| summarize Count=count() by FileDetails, bin(TimeGenerated, $__interval)",
      "resources": [
       "/subscriptions/$Subscription/resourceGroups/$ResourceGroup"
      ],
      "resultFormat": "time_series",
      "workspace": "08934564-b6bd-42d1-9f9f-b777176b0835"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resources": [
       { "resourceGroup": "select", "resourceName": "select" }
      ],
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "9208153d-b7d9-4b82-bbed-8222fc3ed00f"
    }
   ]
  },
  {
   "title": "Block List",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 50 },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "intersectTime": false,
      "query": "AGWFirewallLogs \n| where Action == \"Blocked\"\n| where TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\n| project TimeGenerated, ClientIp, RequestUri, FileDetails",
      "resources": [
       "/subscriptions/$Subscription/resourceGroups/$ResourceGroup"
      ],
      "resultFormat": "table",
      "workspace": "08934564-b6bd-42d1-9f9f-b777176b0835"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resources": [
       { "resourceGroup": "select", "resourceName": "select" }
      ],
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "9208153d-b7d9-4b82-bbed-8222fc3ed00f"
    }
   ]
  }
 ]
}