compressionLevel: mixed

enableGlobalCache: false

yarnPath: .yarn/releases/yarn-4.7.0.cjs

pnpEnableEsmLoader: true

packageExtensions:
  "@kubernetes/client-node@*":
    peerDependencies:
      "ws": "*" # This tells Yarn that @kubernetes/client-node expects ws as a peer dependency
