kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: "{{ .Release.Name }}-mongo-hostvm-configurer"
  labels:
    app: "{{ .Release.Name }}-startup-script"
spec:
  selector:
    matchLabels:
        app: "{{ .Release.Name }}-startup-script"
  updateStrategy:
    type: OnDelete #since 1.16 now default is RollingUpdate
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-startup-script"
    spec:
      hostPID: true
      containers:
      - name: "{{ .Release.Name }}-mongo-hostvm-configurer-container"
        image: gcr.io/google-containers/startup-script:v1
        securityContext:
          privileged: true
        env:
        - name: STARTUP_SCRIPT
          value: |
            #! /bin/bash
            set -o errexit
            set -o pipefail
            set -o nounset

            # Disable hugepages
            echo 'never' > /sys/kernel/mm/transparent_hugepage/enabled
            echo 'never' > /sys/kernel/mm/transparent_hugepage/defrag
