apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    role: mongoclient
spec:
  ports:
  - port: 3000
    targetPort: 3000
  clusterIP: None
  selector:
    role: mongoclient
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deploy
  labels:
    role: mongoclient
spec:
  replicas: 1
  selector:
    matchLabels:
      role: mongoclient
  template:
    metadata:
      labels:
        role: mongoclient
    spec:
      containers:
      - name: "mongoclient"
        image: "mongoclient/mongoclient:2.2.0"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required - Mongo
    nginx.ingress.kubernetes.io/auth-secret: {{ .Values.authSecret }}
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/service-upstream: "true"
  creationTimestamp: null
  name: {{ .Release.Name }}-ingress
spec:
  rules:
  - host: {{ .Values.fqdns }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Release.Name }}-service
            port:
              number: 3000
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - {{ .Values.fqdns }}
    secretName: {{ .Values.tls.secret }}