FROM node:22-alpine
# RUN apk -U upgrade
RUN apk add --no-cache rsync inotify-tools bash gifsicle ffmpeg imagemagick imagemagick-heic xvfb ttf-dejavu ttf-droid ttf-freefont ttf-liberation unifont
RUN mkdir -p /opt/binders
WORKDIR /opt/binders
RUN npm i -g concurrently
ENTRYPOINT [ "/opt/binders/binders-devops-service-v1/app/docker/entrypoint.sh" ]
