install-staging:
	helm install azure-metrics-exporter . -n monitoring -f config/staging.yaml

upgrade-staging:
	helm upgrade --install azure-metrics-exporter . -n monitoring -f config/staging.yaml

install-production:
	helm install azure-metrics-exporter . -n monitoring -f config/production.yaml

upgrade-production:
	helm upgrade --install azure-metrics-exporter . -n monitoring -f config/production.yaml
